#
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md", "AUTHORING.md"]

# Sass configuration
sass:
  sass_dir: _scss

# base url is mainly used for top level sub-directory
baseurl: ""

# the base hostname & protocol for your site
url: "https://lisalaffs.com"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

##########################################
###############   Header   ###############
##########################################

# This is your site title
title: Lisa Laffs
# Website language
lang: en-US
# Header Title
header-title: Lisa Laffs
# Header Tagline
headter-tagline: Live, Love, and Laugh along with Lisa

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: hello@lisalaffs.com

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "#"
google-plus: "#"
vimeo: "#"

#####################################
#############   About   #############
#####################################
about-title: Who Is Lisa
about-description: An online personality with a strange sense of humor and an infectious laugh.

#####################################
#############   Footer   ############
#####################################
footer-description: Find Lisa Laffs on all of your favorite platforms.
footer-copyright-name: Cardillo's Creations, LLC
footer-copyright-year: 2021
